### Get All Users
GET http://localhost:2552/api/users/listAll

### Get Single User
GET http://localhost:3000/users/listOne/62528a8c72a84121b4af5e87

### Insert new User
POST http://localhost:3000/users/addUser
Content-Type: application/json

{
    "firstname": "push testing",
    "lastname": "sivaji",
    "mailid": "pandatamil@gmail.com",
    "role": "owner",
    "phnumber": 2233399900
}

### Update User
PATCH  http://localhost:3000/users/updateUser/61ec4ca3e2c0b50b7e5fe234
Content-Type: application/json

{
    "firstname": "git push testing ",
    "lastname": "kuamr",
    "mailid": "rajkumar@gmail.com",
    "role": "tenent",
    "phnumber": 11234567890
}

### Delete User
DELETE  http://localhost:3000/users/deleteUser/61cae21d0179927162f7c26c

########################################################################

### Get All Homeowners
GET http://localhost:3000/homeowners/listAll

### Get Single Homeowners
GET http://localhost:3000/homeowners/listOne/61cbef1f41454297c3ab041d

### Insert new Homeowners
POST http://localhost:3000/homeowners/addHomeowner
Content-Type: application/json

{
 "first_name": "pandi",
 "last_name": "nandha",
 "mail_address": "pandi@nandha.com",
 "address": {
    "address_line_1": "2/1819 karajer",
    "address_line_2": "viswaii",
    "city": "Vnr",
    "district": "vnr",
    "pincode": 123678,
    "country": "IN"
  },
  "phone_number": 11422333244,
  "reference_id": "IDREF",
  "note": "nandha pandi notes",
  
  "preferences": {
    "email_unsubscribed" : false
  },
   "creation_source": "THIRD-PARTY",
   "version": 0.1
 }

### Update Homeowners

PATCH  http://localhost:3000/homeowners/updateHomeowners/61cb377b1580524caebb1136
Content-Type: application/json
{
 "first_name": "update1",
 "last_name": "sample",
 "mail_address": "sample@example.com",
 "address": {
     "address_line_1": "2/1819 karajer",
     "address_line_2": "viswaii",
     "city": "Vnr",
     "district": "vnr",
     "pincode": 123678,
     "country": "IN"
  },
  "phone_number": 11422333244,
  "reference_id": "IDREF",
  "note": "nandha pandi notes",
 
  "preferences": {
     "email_unsubscribed" : false
   },
  "creation_source": "THIRD-PARTY",
  "version": 0.1
  }
 
### Delete Homeowners
DELETE  http://localhost:3000/homeowners/deleteHomeowner/61cb5f1dbd6a6f8ea1201453
Content-Type: application/json

###Add Property
POST http://localhost:3000/properties/addproperties
Content-Type: application/json

{
    "uploadimg" : "file",
    "streetnumber" : 6789 ,
    "streetname" : "xzyxzty",
    "country" : "us",
    "state" :  "texas" ,
    "city" : "lions",
    "zipcode" : 89885 ,
    "firstname" : "magil",
    "lastname" : "mathi",
    "phone" : 9998989898,
    "email" : "super@gmail.com",
    "yearbuilt" : 1977,
    "area" : 45,
    "lotarea" : 1275 ,
    "bedrooms" : 5,
    "bathrooms" : 3,
    "storey" : 2,
    "ownership" : "owned",
    "duestatus" : "paid"
    "hometype" : "town home",
    "homevalue" : 170000,
    "taxassessment" : 20000
}

###List all properties
GET  http://localhost:3000/properties/listAllproperties

###get single property
GET  http://localhost:3000/properties/getproperty/62597c21fb74c838f30c192e

### Delete property by id
DELETE  http://localhost:3000/properties/deleteproperty/6245279567aed55a83069154